### PR TITLE
Formatting update to match google java format

### PR DESCRIPTION
**Pull request by artado**
Formatting updated across the project, jitpack can is successfully build the project: https://jitpack.io/com/github/artado/Java-OCA-OCPP/4ff7a04fb7/build.log

### CODE REVIEW

**Comment by TVolden** [comment]
This is a huge set of changes. What did you do to apply all these? Run it through some tool?

**Comment by artado** [comment]
Hi Thomas,
I have used the following library: https://github.com/sherter/google-java-format-gradle-plugin
Agree, lots of changes. I was getting an exception from google formatter dependency every time when I was trying to build it in jitpack.io. E.g. see your latest commit exception: https://jitpack.io/com/github/ChargeTimeEU/Java-OCA-OCPP/461ece77df/build.log;
After formatting with the library is was build successfully: https://jitpack.io/com/github/artado/Java-OCA-OCPP/4ff7a04fb7/build.log

**Comment by TVolden** [comment]
There is a failing integration test:
´´´
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.375 s <<< FAILURE! - in eu.chargetime.ocpp.test.profiles.core.json.BootNotificationSpec
[ERROR] Charge point sends Boot Notification and receives a response(eu.chargetime.ocpp.test.profiles.core.json.BootNotificationSpec)  Time elapsed: 1.342 s  <<< FAILURE!
org.spockframework.runtime.SpockTimeoutError: Condition not satisfied after 1.00 seconds and 11 attempts
	at eu.chargetime.ocpp.test.profiles.core.json.BootNotificationSpec.Charge point sends Boot Notification and receives a response(BootNotificationSpec.groovy:27)
Caused by: org.spockframework.runtime.ConditionNotSatisfiedError: 
Condition not satisfied:
chargePoint.recieved(tester.confirmation)
|           |        |      |
|           false    |      BootNotificationConfirmation{currentTime="2020-03-23T22:25:11.237Z[UTC]", interval=42, status=Accepted}
|                    eu.chargetime.ocpp.test.features.BootNotification@63c88994
eu.chargetime.ocpp.test.FakeChargePoint@2e76d0d3
	at eu.chargetime.ocpp.test.profiles.core.json.BootNotificationSpec.Charge point sends Boot Notification and receives a response_closure2(BootNotificationSpec.groovy:28)
	at eu.chargetime.ocpp.test.profiles.core.json.BootNotificationSpec.Charge point sends Boot Notification and receives a response_closure2(BootNotificationSpec.groovy)
	at eu.chargetime.ocpp.test.profiles.core.json.BootNotificationSpec.Charge point sends Boot Notification and receives a response(BootNotificationSpec.groovy:27)
```

It looks like it may be caused by the new date time format. @artado can I get you to look into it?

**Comment by robinroscher** [comment]
Is there any chance this PR gets merged this week?

**Comment by TVolden** [comment]
Hi @robinroscher 

I have been tied up sorry, but I'll try to get some time to look at it. 

Initially I though I only had to fix the problem with the date format, but from what I saw, this won't fix the @xmlElement problem.

**Comment by TVolden** [comment]
I'm currently struggling with JAXB and soap XML. I'm probably going to commit a change with the google format applied. This is most likely going to create merge conflicts with this PR. Sorry.

**Comment by TVolden** [comment]
It looks like jitpack is happy after my latest commit.
https://jitpack.io/#ChargeTimeEU/Java-OCA-OCPP

Please verify.

**Comment by TVolden** [comment]
I'm going to close this PR.
Please pull my changes and create a new PR with the Date component.

**Pull request closed without merging**
