### PR TITLE
Replaces "occurence" with occurrence.

### LINKED ISSUE #216: Word "occurrence" is misspelled
https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/9fe3b7910a15158686887530f09d3d8983ed9c16/ocpp-common/src/main/java/eu/chargetime/ocpp/Session.java#L159-L160

https://github.com/ChargeTimeEU/Java-OCA-OCPP/blob/9fe3b7910a15158686887530f09d3d8983ed9c16/ocpp-common/src/main/java/eu/chargetime/ocpp/OccurenceConstraintException.java#L28

Word occurrence is spelled with double R. This typo is visible not only at source code level, but is sent to the client (see first code snippet). I can fix it, should I do that?

### PR DESCRIPTION
**Pull request by dimaa6**
Fixes #216

### CODE REVIEW

**Comment by dimaa6** [comment]
Fixes #216

**Review by TVolden — APPROVED** [review]
The changes looks good.

**Comment by TVolden** [comment]
Hi @dimaa6,

Thanks for correcting this.

Unfortunately, this will be a breaking change since the exception is placed on the external methods and hence any third-party implementer will (hopefully) have placed a try-catch around the method which may explicitly refer to the exception. :/
I don't see any good way to get around this, that wouldn't introduce the spelling mistake again.

I think the need for a v2 branch is becoming more and more clear, so I'll try to prepare one and eventually move this PR to that branch. I just have to decide how to manage it here on github.

Sincerely,
Thomas

**Comment by dimaa6** [comment]
Good catch, you are right. I did not think about that.

**Comment by TVolden** [comment]
Hi @dimaa6 
I have a v2 branch at which you can target this PR at.

**Comment by dimaa6** [comment]
> Hi @dimaa6 I have a v2 branch at which you can target this PR at.

Hi @TVolden , please look at PR #230

**Comment by TVolden** [comment]
I have merged #230,  so I'll close this one.

**Pull request closed without merging**
