### PR TITLE
Changing Ping interval, added debugging message, fixed Sec-WebSocket-Protocol, and fixed wss

### PR DESCRIPTION
**Pull request by steven-smpct**

### CODE REVIEW

**Comment by steven-smpct** [comment]
Hi Thomas,

The reason I removed the draft was because it wasn't working for me. It may of been because I had a mismatched of the Java-WebSocket library when pulling code and then repaired on the way to the current solution.

I felt the draft increasing code complexity and required you to understand the underlying libraries. This way you keep the abstraction layer and follow examples from the library itself (https://github.com/TooTallNate/Java-WebSocket/wiki/Specifing-a-Sec-WebSocket-Protocol).

Both solutions might work but I didn't have time to test on my system. I prefer my solution because it reduces code complexity and follow standards from the library itself.

Regards,
Steven

**Comment by TVolden** [comment]
Fair enough, I'll take it.

**Comment by TVolden** [comment]
I didn't notice it right away, but all the integration tests are failing on this PR.

**Comment by steven-smpct** [comment]
I don't see the integration tests failing. Below is after mvn clean then mvn test.

`[INFO] ------------------------------------------------------------------------
[INFO] Building Java-OCA-OCPP 0.5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (prepare-agent) @ all ---
[INFO] argLine set to -javaagent:/home/ubuntu/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/home/ubuntu/Work/ocpp-workspace/Java-OCA-OCPP/target/jacoco.exec
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Java-OCA-OCPP common ............................... SUCCESS [  4.374 s]
[INFO] Java-OCA-OCPP v1.6 ................................. SUCCESS [  2.997 s]
[INFO] Java-OCA-OCPP v1.6 - Integration test .............. SUCCESS [  1.429 s]
[INFO] Java-OCA-OCPP ...................................... SUCCESS [  0.210 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.128 s
[INFO] Finished at: 2018-03-13T16:56:58-07:00
[INFO] Final Memory: 32M/570M
[INFO] ------------------------------------------------------------------------`

**Comment by TVolden** [comment]
Sorry for the extreme slow response, but I reintroduced your changes and made them work by adding the protocol to the server as well.

**Pull request merged**
